swagger: "2.0"
info:
  version: "1.0.0"
  title: "Transactions API"
  description: "API endpoints for managing transactions"
paths:
  /transactions:
    get:
      summary: "Get all transactions for the current month"
      description: "Returns a list of all transactions made by the user for the current month"
      parameters:
        - name: "month"
          in: "query"
          description: "The month for which to retrieve transactions (in YYYY-MM format)"
          required: false
          type: "string"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          type: "string"
          required: true
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"
    post:
      summary: "Create a new transaction"
      description: "Creates a new transaction for the current user"
      parameters:
        - name: "transaction"
          in: "body"
          description: "The transaction to create"
          required: true
          schema:
            $ref: "#/definitions/TransactionInput"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          type: "string"
          required: true
      responses:
        201:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Transaction"
        400:
          description: "Bad request"
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"
  /transactions/{id}:
    get:
      summary: "Get the details of a transaction"
      description: "Returns the details of the specified transaction"
      parameters:
        - name: "id"
          in: "path"
          description: "The ID of the transaction to retrieve"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          type: "string"
          required: true
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized"
        404:
          description: "Transaction not found"
        500:
          description: "Internal server error"
    put:
      summary: "Update a transaction"
      description: "Updates the details of the specified transaction"
      parameters:
        - name: "id"
          in: "path"
          description: "The ID of the transaction to update"
          required: true
          type: "integer"
        - name: "transaction"
          in: "body"
          description: "The updated transaction details"
          required: true
          schema:
            $ref: "#/definitions/TransactionInput"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          type: "string"
          required: true
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Transaction"
        400:
          description: "Bad request"
        401:
          description: "Unauthorized"
        404:
          description: "Transaction not found"
        500:
          description: "Internal server error"
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
      date:
        type: "string"
        format: "date-time"
      amount:
        type: "number"
      description:
        type: "string"
  TransactionInput:
    type: "object"
    properties:
      category:
        type: "string"
      note:
        type: "string"
